Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.provider "vmware_workstation" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end

  config.vm.synced_folder "../src/", "/vagrant/src", type: "rsync",
  rsync__exclude: [".git/", "venv/", "*.pyc", "__pycache__/"]
  config.vm.network "forwarded_port", guest: 8000, host: 8088

  config.vm.provision "shell", path: "provision.sh"
end